### ISSUE TITLE
Streaming stop playing audio suddenly but time keeps progressing

### ISSUE THREAD

**Issue by Coehill** [AntennaPod/antennapod.github.io#349]
**Short description**: 
When I stream podcasts, usually if I tap stream then at some point, the audio stops but the time continues as if it's still playing.  To fix it, I have to start playing a different podcast, download the one that failed, then continue playing once it's downloaded. For this reason, I have stopped streaming podcasts altogether and have to download each one.

Logs below. The crash time reported is weeks ago however I had the failure when streaming a podcast today.

## Environment
Android version: 14
OS version: 5.15.123-android13-8-28577312-abS911WVLS3CXD7
AntennaPod version: 3.4.0
Model: SM-S911W
Device: dm1q
Product: dm1qcsx

## Crash info
Time: 10-06-2024 22:39:14
AntennaPod version: 3.4.0

## StackTrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.media.session.MediaSessionCompat.setQueue(java.util.List)' on a null object reference
	at de.danoeh.antennapod.playback.service.PlaybackService.lambda$loadQueueForMediaSession$1(SourceFile:366)
	at de.danoeh.antennapod.playback.service.PlaybackService.$r8$lambda$3WT6xURXkVDC9YruKSvbc6mTkWk(SourceFile:0)
	at de.danoeh.antennapod.playback.service.PlaybackService$$ExternalSyntheticLambda5.accept(SourceFile:0)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(SourceFile:62)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SourceFile:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(SourceFile:124)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by keunes** [comment]
Hi @Coehill
You've created a bug report in the Website repository, but what you describe is an issue with the app, not the website.

It is already reported here: https://github.com/AntennaPod/AntennaPod/issues/7202
